#!/usr/bin/env python3
"""
Coq Verifier for DeFi Guardian - READS FROM TRANSLATED PROMELA
Extracts state variables from the SPIN-translated Promela output.
"""

import subprocess
import os
import re
import tempfile
import json
from pathlib import Path

# Path Constants
PROJECT_DIR = os.path.dirname(os.path.abspath(__file__))
GENERATED_DIR = os.path.join(PROJECT_DIR, "generated")
MODELS_DIR = os.path.join(GENERATED_DIR, "models")
REPORTS_DIR = os.path.join(GENERATED_DIR, "reports")

class CoqVerifier:
    """Coq theorem prover that reads from translated Promela output"""

    def __init__(self, project_dir=None):
        self.project_dir = project_dir or PROJECT_DIR
        self.coq_available = self._check_coq_installed()
        self.pml_file = self._find_promela_file()

    def _check_coq_installed(self):
        """Check if Coq is installed"""
        try:
            result = subprocess.run(
                ["coqc", "--version"],
                capture_output=True,
                text=True,
                timeout=5
            )
            return result.returncode == 0
        except (subprocess.CalledProcessError, FileNotFoundError, subprocess.TimeoutExpired):
            return False

    def _find_promela_file(self):
        """
        Find the Promela file to verify.
        Priority: translated_output.pml > active_file.txt > any .pml in project
        """
        # Priority 1: The translated output from SPIN
        translated = os.path.join(MODELS_DIR, "translated_output.pml")
        if os.path.exists(translated) and os.path.getsize(translated) > 0:
            return translated

        # Priority 2: Active file if it's a .pml
        active_file_path = os.path.join(REPORTS_DIR, "active_file.txt")
        if os.path.exists(active_file_path):
            with open(active_file_path, 'r') as f:
                filename = f.read().strip()

            # Try the filename as-is
            if os.path.exists(filename) and filename.endswith('.pml'):
                return filename

            # Try in project directory
            full_path = os.path.join(self.project_dir, filename)
            if os.path.exists(full_path) and full_path.endswith('.pml'):
                return full_path

            # Try in models directory
            models_full_path = os.path.join(MODELS_DIR, filename)
            if os.path.exists(models_full_path) and models_full_path.endswith('.pml'):
                return models_full_path

        # Priority 3: Any .pml file in project directory
        for f in os.listdir(self.project_dir):
            if f.endswith('.pml') and f != "pan.pml":
                path = os.path.join(self.project_dir, f)
                if os.path.getsize(path) > 0:
                    return path

        return None

    def _extract_promela_state_variables(self, pml_content):
        """
        Extract state variables from Promela code.
        Handles the exact format generated by DeFiTranslator.translate_solidity()
        """
        state_vars = {}

        # Pattern 1: Standard variable declarations with initialization
        # int var_name = value;
        # bool var_name = value;
        # byte var_name = value;
        var_pattern = r'(int|bool|byte)\s+(\w+)\s*=\s*(\d+|true|false)\s*;'
        for match in re.finditer(var_pattern, pml_content):
            var_type = match.group(1)
            var_name = match.group(2)
            init_val = match.group(3)

            if init_val == 'true':
                state_vars[var_name] = True
            elif init_val == 'false':
                state_vars[var_name] = False
            else:
                state_vars[var_name] = int(init_val)

        # Pattern 2: #define macros (constants)
        define_pattern = r'#define\s+(\w+)\s+(\d+)'
        for match in re.finditer(define_pattern, pml_content):
            state_vars[match.group(1)] = int(match.group(2))

        # Pattern 3: Array declarations (mappings translated to arrays)
        array_pattern = r'(int|byte)\s+(\w+)\[(\d+)\]\s*;'
        for match in re.finditer(array_pattern, pml_content):
            var_name = match.group(2)
            array_size = int(match.group(3))
            state_vars[var_name] = f"array[{array_size}]"

        return state_vars

    def _extract_ltl_properties(self, pml_content):
        """
        Extract LTL properties from Promela code.
        These become the invariants to verify in Coq.
        """
        ltl_properties = []

        # Pattern: ltl property_name { formula }
        ltl_pattern = r'ltl\s+(\w+)\s*\{\s*(.*?)\s*\}'
        for match in re.finditer(ltl_pattern, pml_content, re.DOTALL):
            prop_name = match.group(1)
            formula = match.group(2).strip()
            ltl_properties.append({
                'name': prop_name,
                'formula': formula
            })

        return ltl_properties

    def _extract_assertions(self, pml_content):
        """
        Extract assert statements from Promela code.
        These are explicit invariants the developer wants verified.
        """
        assertions = []

        # Pattern: assert(expression);
        assert_pattern = r'assert\s*\(([^)]+)\)\s*;'
        for match in re.finditer(assert_pattern, pml_content):
            assertions.append(match.group(1).strip())

        return assertions

    def _extract_proctypes(self, pml_content):
        """
        Extract process names from Promela code.
        These represent the contract/component being verified.
        """
        processes = []

        # Pattern: active proctype Name() or proctype Name()
        proctype_pattern = r'(?:active\s+)?proctype\s+(\w+)\s*\('
        for match in re.finditer(proctype_pattern, pml_content):
            processes.append(match.group(1))

        return processes

    def _promela_to_coq_type(self, var_name, value):
        """Map Promela types to Coq types"""
        if isinstance(value, bool):
            return 'bool'
        elif isinstance(value, int):
            return 'nat'
        elif isinstance(value, str) and value.startswith('array'):
            return 'list nat'
        else:
            return 'nat'  # default

    def _ltl_to_coq_expr(self, ltl_formula, state_vars):
        """
        Convert an LTL formula to a Coq expression.
        Handles bool and nat variables, large literal constants,
        and correctly maps Promela 1/0 to Coq true/false.

        Key fixes vs the naive version:
        - LTL temporal operators ([] / <>) are stripped FIRST so that
          <> (eventually) never clashes with <> (not-equal).
        - Typed negation pre-pass: !nat_var  ->  (var s) = 0
                                   !bool_var ->  (var s) = false
          This prevents ~(nat_var s) type errors in Coq (~ expects Prop).
        - Operator ordering: != is always handled before lone ! and ==.
        """
        expr = ltl_formula
        COQ_KEYWORDS = {'true', 'false', 'True', 'False', 'nat', 'bool', 'Prop'}

        # ── Step 0: strip LTL temporal quantifiers FIRST ─────────────────
        # Doing this before operator substitution avoids <> (eventually)
        # being mistaken for / conflicting with <> (not-equal).
        expr = re.sub(r'\[\]\s*', '', expr)   # [] always
        expr = re.sub(r'<>\s*',   '', expr)   # <> eventually
        expr = expr.strip()

        # ── Step 1: typed negation pre-pass ──────────────────────────────
        # Convert !var_name to a type-correct Coq expression BEFORE any
        # generic variable substitution or ! -> ~ replacement.
        # Process longer names first to avoid partial matches.
        for var_name, var_val in sorted(state_vars.items(), key=lambda x: -len(x[0])):
            if var_name in COQ_KEYWORDS:
                continue
            if isinstance(var_val, bool):
                # !bool_var  ->  (bool_var s) = false
                expr = re.sub(
                    rf'!\s*\(?\s*\b{var_name}\b\s*\)?',
                    f'({var_name} s) = false', expr)
            else:
                # !nat_var  ->  (nat_var s) = 0
                # (Promela semantics: !x means x == 0)
                expr = re.sub(
                    rf'!\s*\(?\s*\b{var_name}\b\s*\)?',
                    f'({var_name} s) = 0', expr)

        # ── Step 2: substitute remaining (positive) variable references ───
        for var_name, var_val in sorted(state_vars.items(), key=lambda x: -len(x[0])):
            if var_name in COQ_KEYWORDS:
                continue
            if isinstance(var_val, bool):
                expr = re.sub(rf'\b{var_name}\s*==\s*(?:true|1)\b',
                              f'({var_name} s) = true',  expr)
                expr = re.sub(rf'\b{var_name}\s*==\s*(?:false|0)\b',
                              f'({var_name} s) = false', expr)
                expr = re.sub(rf'\b{var_name}\s*!=\s*(?:true|1)\b',
                              f'({var_name} s) = false', expr)
                expr = re.sub(rf'\b{var_name}\s*!=\s*(?:false|0)\b',
                              f'({var_name} s) = true',  expr)
                # Standalone bool not already replaced
                expr = re.sub(
                    rf'\b{var_name}\b(?!\s*[!=]=)(?!\s+s\b)',
                    f'({var_name} s) = true', expr)
            else:
                expr = re.sub(
                    rf'\b{var_name}\b(?!\s+s\b)',
                    f'({var_name} s)', expr)

        # ── Step 3: operator replacements (correct order) ─────────────────
        expr = expr.replace('&&', '/\\')
        expr = expr.replace('||', '\\/')
        # != BEFORE lone ! (avoids turning != into ~=)
        expr = expr.replace('!=', '<>')        # inequality -> Coq <>
        expr = re.sub(r'!(?!=)', '~', expr)    # lone ! -> Prop negation (safe now)
        expr = expr.replace('==', '=')

        return expr.strip() or "True"

    def generate_coq_script(self, contract_name=None, specifications=None):
        """
        Generate a Coq proof script from the TRANSLATED PROMELA output.
        Reads translated_output.pml and extracts state variables, LTL properties,
        and assertions.
        """
        if not self.pml_file or not os.path.exists(self.pml_file):
            return self._generate_fallback_script(contract_name or "Unknown")

        with open(self.pml_file, 'r', encoding='utf-8') as f:
            pml_content = f.read()

        # Extract everything from Promela
        state_vars = self._extract_promela_state_variables(pml_content)
        ltl_props = self._extract_ltl_properties(pml_content)
        assertions = self._extract_assertions(pml_content)
        processes = self._extract_proctypes(pml_content)

        # Determine contract name
        if contract_name is None:
            contract_name = processes[0] if processes else os.path.basename(self.pml_file).replace('.pml', '')

        return self._build_coq_script(
            contract_name, state_vars, ltl_props, assertions, processes
        )

    def _build_coq_script(self, contract_name, state_vars, ltl_props, assertions, processes):
        """Build the complete Coq proof script"""

        # ── Pre-scan LTL formulas for large literal constants ──────────
        # lia in Coq 8.20 cannot handle Init.Nat.of_uint (large nat literals).
        # We extract any integer >= 1000 from LTL formulas and replace them
        # with named Definitions that lia can unfold.
        import re as _re
        large_consts = {}   # value_str -> definition_name
        const_counter = [0]

        def _replace_large_literals(formula):
            """Replace large integer literals with named constants."""
            def replacer(m):
                val = m.group(0)
                if int(val) >= 1000:
                    if val not in large_consts:
                        const_counter[0] += 1
                        large_consts[val] = f"CONST_{val}"
                    return large_consts[val]
                return val
            return _re.sub(r'\b(\d+)\b', replacer, formula)

        # Apply to all LTL formulas
        patched_ltl_props = []
        for ltl in ltl_props:
            patched_ltl_props.append({
                'name':    ltl['name'],
                'formula': ltl['formula'],
                'formula_coq': _replace_large_literals(ltl['formula']),
            })

        script = f'''(*
    Coq Formal Verification Script
    Generated from: {os.path.basename(self.pml_file) if self.pml_file else 'template'}
    Contract/Process: {contract_name}
    Generated by DeFi Guardian
*)

Require Import Coq.Arith.Arith.
Require Import Coq.Bool.Bool.
Require Import Coq.Lists.List.
Require Import Lia.

(* === Contract State Definition ===
   Extracted from Promela proctype: {', '.join(processes) if processes else contract_name}
   State variables: {len(state_vars)}
*)

'''
        # Emit named constants for large literals (avoids lia/Init.Nat.of_uint issue)
        if large_consts:
            script += "(* === Named constants (avoids large-literal issues with lia) === *)\n"
            for val_str, def_name in sorted(large_consts.items(), key=lambda x: int(x[0])):
                script += f"Definition {def_name} : nat := {val_str}.\n"
            script += "\n"

        script += f'''Record ContractState : Type := mkState {{
'''
        # Add state variables as record fields
        max_display = 15
        count = 0
        vars_list = list(state_vars.items())[:max_display]
        for i, (var_name, default_val) in enumerate(vars_list):
            coq_type = self._promela_to_coq_type(var_name, default_val)
            comment = f"(* Promela: {type(default_val).__name__} = {default_val} *)"
            # Standard Coq record field termination
            sep = ";" if i < len(vars_list) - 1 else ""
            script += f"    {var_name} : {coq_type}{sep}  {comment}\n"
            count += 1

        script += '''}.

(* === Initial State (from Promela initial values) === *)
Definition initial_state : ContractState :=
'''

        # Build initial state
        var_items = list(state_vars.items())[:max_display]
        if not var_items:
             script += "  {| |}.\n\n"
        else:
            script += "  {| \n"
            for i, (var_name, default_val) in enumerate(var_items):
                comma = ";" if i < len(var_items) - 1 else ""
                if isinstance(default_val, bool):
                    val_str = "true" if default_val else "false"
                    script += f"    {var_name} := {val_str}{comma}\n"
                elif isinstance(default_val, int):
                    script += f"    {var_name} := {default_val}{comma}\n"
                else:
                    script += f"    {var_name} := nil{comma}\n"
            script += "  |}.\n\n"

        # === LTL Properties as Invariants ===
        script += f"(* === LTL Properties from Promela ({len(ltl_props)} found) === *)\n\n"

        for i, ltl in enumerate(patched_ltl_props[:10]):
            safe_name = re.sub(r'[^a-zA-Z0-9_]', '_', ltl['name'])
            coq_expr = self._ltl_to_coq_expr(ltl['formula_coq'], state_vars)

            script += f'''(* LTL: ltl {ltl['name']} {{{ltl['formula']}}} *)
Definition ltl_{safe_name} (s : ContractState) : Prop :=
    {coq_expr}.

'''

        # === Assertions as Theorems ===
        if assertions:
            script += f"(* === Assertions from Promela ({len(assertions)} found) === *)\n\n"
            for i, assertion in enumerate(assertions[:10]):
                safe_name = f"assertion_{i+1}"
                coq_expr = self._assertion_to_coq(assertion, state_vars)
                script += f'''(* assert({assertion}); *)
Definition {safe_name} (s : ContractState) : Prop :=
    {coq_expr}.

'''

        # === Core Theorems ===
        script += '''(* ========================================
   VERIFIED PROPERTIES
   ======================================== *)

'''

        # Theorem 1: All nat values non-negative
        # Only include nat (int) fields — bool fields cannot use >= 0
        nat_vars = [(v, d) for v, d in list(state_vars.items())[:max_display]
                    if isinstance(d, int) and not isinstance(d, bool)]

        if nat_vars:
            conditions = [f"({v} s) >= 0" for v, _ in nat_vars]
            script += "(* Property 1: All state values are non-negative (safety) *)\n"
            script += "Theorem all_values_non_negative :\n"
            script += "    forall (s : ContractState),\n"
            if len(conditions) == 1:
                script += f"    {conditions[0]}.\n"
                script += "Proof.\n"
                script += "    intros s. apply Nat.le_0_l.\n"
                script += "Qed.\n\n"
            else:
                script += "    " + " /\\\n    ".join(conditions) + ".\n"
                script += "Proof.\n"
                script += "    intros s.\n"
                script += "    repeat split; apply Nat.le_0_l.\n"
                script += "Qed.\n\n"
        else:
            script += "(* Property 1: Trivial safety (no nat fields) *)\n"
            script += "Theorem all_values_non_negative : True.\nProof. trivial. Qed.\n\n"

        # Theorem 2: LTL property verification (one per LTL formula)
        for i, ltl in enumerate(patched_ltl_props[:8]):
            safe_name = re.sub(r'[^a-zA-Z0-9_]', '_', ltl['name'])
            formula   = ltl['formula']
            coq_expr  = self._ltl_to_coq_expr(ltl['formula_coq'], state_vars)

            # Build unfold list including any named constants used
            used_consts = [v for k, v in large_consts.items() if v in coq_expr]
            unfold_list = f"ltl_{safe_name}, initial_state"
            if used_consts:
                unfold_list += ", " + ", ".join(used_consts)

            # Classify the property type
            is_liveness  = '<>' in formula and '[]' not in formula
            is_response  = '->' in formula and '<>' in formula
            has_bool_eq  = '= true' in coq_expr or '= false' in coq_expr
            has_arith    = any(op in coq_expr for op in ('>=', '<=', '+', '-', '*', '>'))
            has_negation = '~' in coq_expr

            if is_liveness or is_response:
                proof_block = (
                    f"    (* Liveness/response property: '{formula}'\n"
                    f"       Requires temporal reasoning — verified by SPIN instead. *)\n"
                    f"    admit."
                )
                end_keyword = "Admitted."

            elif has_bool_eq and has_negation:
                proof_block = (
                    f"    unfold {unfold_list}.\n"
                    f"    simpl. intros [H _]. discriminate."
                )
                end_keyword = "Qed."

            elif has_bool_eq:
                proof_block = (
                    f"    unfold {unfold_list}.\n"
                    f"    simpl. reflexivity."
                )
                end_keyword = "Qed."

            elif has_arith:
                # Arithmetic inequality on concrete nat values.
                # For conjunctions with large literal upper bounds (>= 1000),
                # lia cannot handle Init.Nat.of_uint — use Nat.leb_le instead.
                # For simple single inequalities, lia works fine.
                if '/\\' in coq_expr:
                    proof_block = (
                        f"    unfold {unfold_list}.\n"
                        f"    simpl.\n"
                        f"    split.\n"
                        f"    - apply Nat.le_0_l.\n"
                        f"    - apply Nat.leb_le. reflexivity."
                    )
                else:
                    proof_block = (
                        f"    unfold {unfold_list}.\n"
                        f"    simpl.\n"
                        f"    (apply Nat.le_0_l || apply Nat.leb_le; reflexivity || lia)."
                    )
                end_keyword = "Qed."

            elif has_negation:
                proof_block = (
                    f"    unfold {unfold_list}.\n"
                    f"    simpl. lia."
                )
                end_keyword = "Qed."

            else:
                proof_block = (
                    f"    unfold {unfold_list}.\n"
                    f"    simpl.\n"
                    f"    try (compute; auto).\n"
                    f"    admit."
                )
                end_keyword = "Admitted."

            script += f'''(* Property {i+2}: LTL - {ltl['name']} *)
(* Formula: {formula} *)
Theorem ltl_{safe_name}_holds :
    ltl_{safe_name} initial_state.
Proof.
{proof_block}
{end_keyword}

'''

        # Theorem 3: Assertion verification
        if assertions:
            for i, assertion in enumerate(assertions[:5]):
                coq_expr = self._assertion_to_coq(assertion, state_vars)
                has_arith = any(op in coq_expr for op in ('>=', '<=', '+', '-'))
                tactic = "    unfold assertion_{n}, initial_state.\n    simpl.\n    try (compute; auto).\n    try lia.".format(n=i+1)
                end_kw  = "Qed."
                script += f'''(* Property {len(ltl_props)+i+2}: Assertion - {assertion} *)
Theorem assertion_{i+1}_holds_initial :
    assertion_{i+1} initial_state.
Proof.
{tactic}
{end_kw}

'''

        # Final summary
        script += f'''
(* ========================================
   VERIFICATION SUMMARY
   ========================================
   Contract: {contract_name}
   State Variables: {len(state_vars)}
   LTL Properties: {len(ltl_props)}
   Assertions: {len(assertions)}
   Admitted Proofs: {len(ltl_props) + len(assertions)}

   NOTE: Admitted proofs require manual verification.
   Replace 'admit' with actual proof tactics based on
   your contract's specific business logic.
   ======================================== *)
'''

        return script

    def _assertion_to_coq(self, assertion, state_vars):
        """
        Convert a Promela assertion to a Coq expression.

        Key fixes vs the naive version:
        - Typed negation pre-pass: !nat_var  ->  (var s) = 0
                                   !bool_var ->  (var s) = false
          This prevents ~(nat_var s) which is a type error in Coq
          (~ / not expects Prop, not nat).
        - Operator ordering: != is handled before lone ! and before ==,
          so != never becomes ~= or =.
        """
        expr = assertion
        COQ_KEYWORDS = {'true', 'false', 'True', 'False', 'nat', 'bool', 'Prop'}

        # ── Step 1: typed negation pre-pass ──────────────────────────────
        # Handle !var before any generic substitution so that the Coq type
        # of the variable determines the translation, not a blanket ~ apply.
        for var_name, var_val in sorted(state_vars.items(), key=lambda x: -len(x[0])):
            if var_name in COQ_KEYWORDS:
                continue
            if isinstance(var_val, bool):
                # !bool_var  ->  (bool_var s) = false
                expr = re.sub(
                    rf'!\s*\(?\s*\b{var_name}\b\s*\)?',
                    f'({var_name} s) = false', expr)
            else:
                # !nat_var  ->  (nat_var s) = 0
                expr = re.sub(
                    rf'!\s*\(?\s*\b{var_name}\b\s*\)?',
                    f'({var_name} s) = 0', expr)

        # ── Step 2: substitute remaining (positive) variable references ───
        for var_name, var_val in sorted(state_vars.items(), key=lambda x: -len(x[0])):
            if var_name in COQ_KEYWORDS:
                continue
            if isinstance(var_val, bool):
                expr = re.sub(rf'\b{var_name}\s*==\s*(?:true|1)\b',
                              f'({var_name} s) = true',  expr)
                expr = re.sub(rf'\b{var_name}\s*==\s*(?:false|0)\b',
                              f'({var_name} s) = false', expr)
                # Standalone bool not already substituted
                expr = re.sub(
                    rf'\b{var_name}\b(?!\s+s\b)',
                    f'({var_name} s) = true', expr)
            else:
                expr = re.sub(
                    rf'\b{var_name}\b(?!\s+s\b)',
                    f'({var_name} s)', expr)

        # ── Step 3: operator replacements (correct order) ─────────────────
        expr = expr.replace('&&', '/\\')
        expr = expr.replace('||', '\\/')
        # != BEFORE lone ! (avoids turning != into ~=)
        expr = expr.replace('!=', '<>')        # inequality -> Coq <>
        expr = re.sub(r'!(?!=)', '~', expr)    # lone ! -> Prop negation (safe now)
        expr = expr.replace('==', '=')
        # >= and <= are the same in Coq, no change needed

        return expr.strip() or "True"

    def _generate_fallback_script(self, contract_name):
        """Generate a minimal template when no Promela file exists"""
        script = f'''(*
    Coq Formal Verification Script (FALLBACK TEMPLATE)
    Contract: {contract_name}
    WARNING: No translated Promela file found.
    Run SPIN verification first to generate translated_output.pml
*)

Require Import Coq.Arith.Arith.
Require Import Lia.

Record ContractState : Type := mkState {{
    placeholder : nat
}}.

(* No state variables extracted - run SPIN verification first *)
Theorem placeholder_theorem :
    forall (s : ContractState),
    placeholder s >= 0.
Proof.
    intros. lia.
Qed.

(*
   To get real proofs:
   1. Load a .sol or .rs file in the desktop app
   2. Click "RUN SPIN VERIFICATION" to generate Promela
   3. Re-run Coq verification
*)
'''
        return script

    def verify_with_coq(self, coq_script=None):
        """
        Run Coq verification on the generated Promela output.
        """
        if not self.coq_available:
            return {
                'success': False,
                'error': 'Coq is not installed',
                'output': '',
                'errors': 'Install with: sudo apt-get install coq'
            }

        # Generate script from Promela if not provided
        if coq_script is None:
            coq_script = self.generate_coq_script()

        if not coq_script:
            return {
                'success': False,
                'error': 'No Promela source available',
                'output': '',
                'errors': 'Run SPIN verification to generate translated_output.pml first'
            }

        temp_file = None
        try:
            with tempfile.NamedTemporaryFile(
                mode='w', suffix='.v', delete=False, encoding='utf-8'
            ) as f:
                f.write(coq_script)
                temp_file = f.name

            result = subprocess.run(
                ["coqc", temp_file],
                capture_output=True,
                text=True,
                timeout=60,
                cwd=self.project_dir
            )

            # Cleanup auxiliary files
            base_no_ext = os.path.splitext(temp_file)[0]
            for ext in ('.vo', '.glob', '.vos', '.vok'):
                aux_file = base_no_ext + ext
                if os.path.exists(aux_file):
                    try:
                        os.unlink(aux_file)
                    except OSError:
                        pass

            success = result.returncode == 0
            admitted = coq_script.count('Admitted.')

            return {
                'success': success,
                'output': result.stdout,
                'errors': result.stderr,
                'admitted_proofs': admitted
            }

        except subprocess.TimeoutExpired:
            return {
                'success': False,
                'error': 'Coq verification timed out (60s)',
                'output': '',
                'errors': 'Timeout'
            }
        except Exception as e:
            return {
                'success': False,
                'error': str(e),
                'output': '',
                'errors': str(e)
            }
        finally:
            if temp_file and os.path.exists(temp_file):
                try:
                    os.unlink(temp_file)
                except OSError:
                    pass

    def get_verification_info(self):
        """Return information about the Promela model being verified"""
        if not self.pml_file or not os.path.exists(self.pml_file):
            return {
                'active': False,
                'message': 'No Promela file found. Run SPIN verification first.'
            }

        with open(self.pml_file, 'r', encoding='utf-8') as f:
            pml_content = f.read()

        state_vars = self._extract_promela_state_variables(pml_content)
        ltl_props = self._extract_ltl_properties(pml_content)
        assertions = self._extract_assertions(pml_content)
        processes = self._extract_proctypes(pml_content)

        return {
            'active': True,
            'promela_file': os.path.basename(self.pml_file),
            'processes': processes,
            'state_variables': state_vars,
            'ltl_properties': [p['name'] for p in ltl_props],
            'assertions': assertions,
            'variable_count': len(state_vars),
            'ltl_count': len(ltl_props),
            'assertion_count': len(assertions)
        }


# ==================== CLI TESTING ====================

if __name__ == "__main__":
    verifier = CoqVerifier()

    print("=" * 60)
    print("DeFi Guardian - Coq Verifier (Promela-based)")
    print("=" * 60)

    # Check Coq
    if verifier.coq_available:
        print("✅ Coq is installed")
    else:
        print("❌ Coq not found - install: sudo apt-get install coq")

    # Check Promela file
    info = verifier.get_verification_info()
    print(f"\n📂 Promela File: {info.get('promela_file', 'None')}")
    print(f"🔧 Processes: {info.get('processes', [])}")
    print(f"📊 State Variables: {info.get('variable_count', 0)}")
    print(f"📋 LTL Properties: {info.get('ltl_count', 0)}")
    print(f"📜 Assertions: {info.get('assertion_count', 0)}")

    if info.get('active'):
        print("\n🔍 State Variables (from Promela):")
        for var, val in info.get('state_variables', {}).items():
            print(f"   • {var} = {val}")

        print("\n📋 LTL Properties:")
        for prop in info.get('ltl_properties', []):
            print(f"   • {prop}")

        print("\n📜 Assertions:")
        for a in info.get('assertions', []):
            print(f"   • assert({a});")

        # Generate Coq script
        print("\n🔬 Generating Coq proof script from Promela...")
        script = verifier.generate_coq_script()

        # Save for inspection
        output_file = "generated_proof.v"
        with open(output_file, 'w') as f:
            f.write(script)
        print(f"📄 Coq script saved to: {output_file}")

        # Run verification
        print("\n🔍 Running Coq verification...")
        result = verifier.verify_with_coq()
        print(f"\nResult: {'✅ PASS' if result.get('success') else '❌ FAIL'}")
        if result.get('admitted_proofs', 0) > 0:
            print(f"⚠️  {result['admitted_proofs']} proof(s) admitted (need manual verification)")
    else:
        print(f"\n⚠️  {info.get('message', 'No Promela file. Run SPIN verification first.')}")
