import subprocess
import os
import tempfile
import shutil

class LeanVerifier:
    """Lean theorem prover integration"""
    
    def __init__(self):
        self.lean_available = self._check_lean_installed()
    
    def _check_lean_installed(self):
        """Check if Lean is installed"""
        try:
            subprocess.run(["lean", "--version"], capture_output=True, check=True)
            return True
        except (subprocess.CalledProcessError, FileNotFoundError):
            return False
    
    def generate_lean_script(self, contract_name, specifications):
        lines = [
            "-- Lean 4 Proof Script for " + contract_name,
            "-- Generated by DeFi Guardian",
            "",
            "structure ContractState where",
            "  collateral   : Nat",
            "  debt         : Nat",
            "  price        : Nat",
            "  lock         : Bool",
            "  healthFactor : Nat",
            "",
            "def invariantCollateral (s : ContractState) : Prop :=",
            "  s.collateral * s.price >= s.debt",
            "",
            "def safeOperation (s : ContractState) : ContractState :=",
            "  if s.lock then s",
            "  else ContractState.mk s.collateral s.debt s.price true",
            "         ((s.collateral * s.price) / s.debt)",
            "",
            "theorem conservation (s : ContractState) (h : invariantCollateral s) :",
            "    invariantCollateral (safeOperation s) := by",
            "  unfold invariantCollateral safeOperation",
            "  split",
            "  . exact h",
            "  . simp",
            "    exact h",
            "",
            "theorem reentrancySafety (s : ContractState) (h : s.lock = false) :",
            "    (safeOperation s).lock = true := by",
            "  simp [safeOperation, h]",
        ]
        return "\n".join(lines)
    
    def verify_with_lean(self, lean_script):
        """
        Verify a Lean 4 script by scaffolding a minimal Lake project.

        FIX: Lean 4 cannot verify a bare .lean file that contains theorems
        without a surrounding Lake project — it will time out waiting for
        environment setup or simply fail to elaborate. We create a throwaway
        Lake project (no Mathlib dependency needed for pure Nat/Bool proofs)
        so that `lake build` gives Lean the correct build environment.
        """
        if not self.lean_available:
            return {
                'success': False,
                'error': 'Lean not installed or not on PATH',
                'output': ''
            }

        project_dir = None
        try:
            project_dir = tempfile.mkdtemp(prefix="lean_verify_")

            # --- lakefile.lean ------------------------------------------
            # A minimal Lake project: one library target, no external deps.
            lakefile = (
                'import Lake\nopen Lake DSL\n\n'
                'package «defi_guardian» where\n\n'
                'lean_lib «DefiGuardian» where\n'
            )
            with open(os.path.join(project_dir, 'lakefile.lean'), 'w') as f:
                f.write(lakefile)

            # lean-toolchain — pin to whatever `lean --version` reports so
            # Lake doesn't try to download a different toolchain.
            try:
                ver_result = subprocess.run(
                    ["lean", "--version"], capture_output=True, text=True, timeout=5
                )
                # Output is like: "Lean (version 4.x.y, ...)"
                import re
                m = re.search(r'version\s+([\d.]+)', ver_result.stdout)
                toolchain = f"leanprover/lean4:v{m.group(1)}" if m else "leanprover/lean4:stable"
            except Exception:
                toolchain = "leanprover/lean4:stable"

            with open(os.path.join(project_dir, 'lean-toolchain'), 'w') as f:
                f.write(toolchain + '\n')

            # --- Source file --------------------------------------------
            # Lake expects source files under a directory named after the
            # library (DefiGuardian/ here).
            src_dir = os.path.join(project_dir, 'DefiGuardian')
            os.makedirs(src_dir)
            with open(os.path.join(src_dir, 'Verify.lean'), 'w') as f:
                f.write(lean_script)

            # Root module file required by Lake
            with open(os.path.join(project_dir, 'DefiGuardian.lean'), 'w') as f:
                f.write('import DefiGuardian.Verify\n')

            # --- Run Lake build -----------------------------------------
            # Use `lake build` rather than bare `lean file.lean`.
            # Timeout raised to 60 s; pure Nat proofs compile quickly.
            result = subprocess.run(
                ["lake", "build"],
                capture_output=True,
                text=True,
                timeout=60,
                cwd=project_dir
            )

            success = result.returncode == 0
            return {
                'success': success,
                'output': result.stdout,
                'errors': result.stderr if not success else '',
                'error': (result.stderr[:300] if not success else '')
            }

        except subprocess.TimeoutExpired:
            return {
                'success': False,
                'error': 'Lean timed out (60s). Ensure `lake` is on PATH.',
                'output': '',
                'errors': 'Timeout'
            }
        except Exception as e:
            return {'success': False, 'error': str(e), 'output': '', 'errors': str(e)}
        finally:
            if project_dir and os.path.exists(project_dir):
                try:
                    shutil.rmtree(project_dir)
                except Exception:
                    pass