/* 
  * Auto-generated Certora Specification 
  * Contract: IERC3156FlashBorrower 
  * Generated by DeFi Guardian 
  */ 
 
 methods { 
     // Declare your contract's external functions here 
     // function yourFunction(address, uint256) external returns (uint256) envfree; 
 } 
 
 // Rule: Basic sanity check - constructor doesn't revert 
 rule constructorSanity() { 
     constructor(); 
     assert true, "Constructor should complete"; 
 } 
 
 // Rule: No function should revert unexpectedly 
 rule noUnexpectedRevert(method f) { 
     calldataarg args; 
     f@withrevert(e, args); 
     
     // Log reverts for analysis (doesn't fail the rule) 
     // Remove the comment below to fail on unexpected reverts: 
     // assert !lastReverted, "Unexpected revert"; 
 } 
 
 // TODO: Add your contract-specific rules here 
 // See: https://docs.certora.com/ 
 