/*
 * Certora Specification — Kabvote
 * Generated by DeFi Guardian
 *
 * Patterns used:
 *   - envfree: declare view functions that don't read msg.sender
 *   - Symbolic variables: prover finds violating assignments automatically
 *   - method f + calldataarg: check a property holds across ALL methods
 */

methods {
    // Declare envfree functions (pure view, no msg.sender dependency):
    // function yourView(address) external returns (uint256) envfree;
}

// ─── Rule: No function should revert unexpectedly ───────────────────────────
rule noUnexpectedRevert(method f) {
    calldataarg args;
    f@withrevert(e, args);
    // Uncomment to enforce no reverts:
    // assert !lastReverted, "Unexpected revert in " + f.selector;
    satisfy true;
}

// ─── Rule: State variable X never decreases (template) ──────────────────────
// rule xMonotonicallyIncreases(method f) {
//     uint256 x_before = getX();
//     calldataarg args;
//     f(e, args);
//     assert getX() >= x_before, "X must never decrease";
// }

// ─── Rule: Only owner can change critical state (template) ──────────────────
// rule onlyOwnerCanChange(method f) {
//     uint256 state_before = criticalState();
//     calldataarg args;
//     f(e, args);
//     assert criticalState() != state_before => e.msg.sender == owner(),
//         "Only owner may change critical state";
// }
